# Generated by Django 4.1.5 on 2023-01-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customers",
            name="address",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AddField(
            model_name="customers",
            name="email",
            field=models.EmailField(default="", max_length=220),
        ),
        migrations.AddField(
            model_name="customers",
            name="mobil_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="customers",
            name="name",
            field=models.CharField(default="", max_length=220),
        ),
        migrations.AddField(
            model_name="customers",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="customers",
            name="postcode",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="employees",
            name="address",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AddField(
            model_name="employees",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employees",
            name="email",
            field=models.EmailField(default="", max_length=220),
        ),
        migrations.AddField(
            model_name="employees",
            name="first_name",
            field=models.CharField(default="", max_length=220),
        ),
        migrations.AddField(
            model_name="employees",
            name="gender",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male")], default="", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="employees",
            name="job_title",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="employees",
            name="last_name",
            field=models.CharField(default="", max_length=220),
        ),
        migrations.AddField(
            model_name="employees",
            name="mobil_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="employees",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="employees",
            name="postcode",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="suppliers",
            name="address",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AddField(
            model_name="suppliers",
            name="email",
            field=models.EmailField(default="", max_length=220),
        ),
        migrations.AddField(
            model_name="suppliers",
            name="mobil_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="suppliers",
            name="name",
            field=models.CharField(default="", max_length=220),
        ),
        migrations.AddField(
            model_name="suppliers",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="suppliers",
            name="postcode",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
