# Generated by Django 4.1.5 on 2023-01-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_customers_address_customers_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customers", old_name="name", new_name="company_name",
        ),
        migrations.RenameField(
            model_name="suppliers", old_name="name", new_name="company_name",
        ),
        migrations.AddField(
            model_name="customers",
            name="first_name",
            field=models.CharField(default="", max_length=220),
        ),
        migrations.AddField(
            model_name="customers",
            name="gender",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male")], default="", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="customers",
            name="job_title",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="customers",
            name="last_name",
            field=models.CharField(default="", max_length=220),
        ),
        migrations.AddField(
            model_name="customers",
            name="tax_id",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="employees",
            name="company_name",
            field=models.CharField(default="", max_length=220),
        ),
        migrations.AddField(
            model_name="suppliers",
            name="first_name",
            field=models.CharField(default="", max_length=220),
        ),
        migrations.AddField(
            model_name="suppliers",
            name="gender",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male")], default="", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="suppliers",
            name="job_title",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="suppliers",
            name="last_name",
            field=models.CharField(default="", max_length=220),
        ),
        migrations.AddField(
            model_name="suppliers",
            name="website",
            field=models.URLField(blank=True, default="", max_length=220),
        ),
        migrations.AlterField(
            model_name="employees",
            name="birthday",
            field=models.DateField(blank=True, default="", null=True),
        ),
    ]
