# Generated by Django 4.1.5 on 2023-01-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_rename_name_customers_company_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="gender",
            field=models.CharField(
                choices=[("", "----"), ("F", "Female"), ("M", "Male")],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="employees",
            name="gender",
            field=models.CharField(
                choices=[("", "----"), ("F", "Female"), ("M", "Male")],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="suppliers",
            name="gender",
            field=models.CharField(
                choices=[("", "----"), ("F", "Female"), ("M", "Male")],
                default="",
                max_length=20,
            ),
        ),
    ]
