# Generated by Django 4.1.5 on 2023-01-20 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_taxes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxes",
            name="account_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounting.chartofaccounts",
            ),
        ),
    ]
