# Generated by Django 4.1.5 on 2023-01-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_alter_currency_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency", name="abbrev", field=models.CharField(max_length=10),
        ),
    ]
