# Generated by Django 4.1.5 on 2023-01-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0006_alter_currency_abbrev"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chartofaccounts", options={"ordering": ["code"]},
        ),
        migrations.AlterField(
            model_name="chartofaccounts",
            name="code",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
